

easy:
    resource: "@EasyBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation


users:
    resource: "@UsersBundle/Controller/"
    type:     annotation
    prefix:   /users



logout:
  path: users/logout
