# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        UsersBundle\Entity\User: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:

        our_db_provider:

          entity:

            class: UsersBundle:User
            property: username

        in_memory:
            memory:
                users:
                    admin:
                        password: 1234
                        roles: 'ROLE_ADMIN'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs

        dev:

            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: ^/admin
            http_basic: ~

        users:

            pattern: ^/
            anonymous: ~
            provider: our_db_provider

            form_login:
                login_path: /users/login
                check_path: /users/login
                default_target_path: /

            logout:
                path:   /users/logout
                target: /users/login



        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html



    access_control:
            - { path: ^/users/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/users/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/usuarios/conf, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin, roles: ROLE_ADMIN }
            - { path: ^/users/admin, roles: ROLE_ADMIN }
